// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqbcueburnerofmvdevg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYmN1ZWJ1cm5lcm9mbXZkZXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzE0MjYsImV4cCI6MjA3Mzg0NzQyNn0.QsPvEWafXm65SNO_82DOLXaXwllkuPXV4-1oc2jwJnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});